name: Pl3xshiftvanish
version: '${project.version}'
main: me.jules.pl3xshiftvanish.Pl3xshiftvanish
api-version: 1.19
authors: [ ItsJules_ ]
description: Vanishes your players when they shift in pl3xmap!
